### ISSUE TITLE
BUG: Class Bonfire\Config\Events.php has not been updated

### ISSUE THREAD

**Issue by andersonsousaferreira** [lonnieezell/Bonfire2#1]
Class not updated for new Settings changes.

**Comment by andersonsousaferreira** [comment]
I'm your fan. Thanks for everything, this will change my life for the better yet and I won't forget to be generous to you.

**Comment by lonnieezell** [comment]
Hey @andersonsousaferreira Thanks for letting me know. I had a bunch of changes with implementing the Email settings page I was sifting through and likely just missed the file. I will double check tonight.
