### ISSUE TITLE
registering user

### ISSUE THREAD

**Issue by rjwmtgevolution** [lonnieezell/Bonfire2#105]
Hi Lonnie,

I was trying to register a new user on my system that I installed bonfire2.

on the backend I enabled ,Force email verification after registration? and Force 2FA check after login?

I do have SMTP enabled using sendgrid for sending emails

When I registered the user with the above setup, I was redirected to
http://{myurl}/auth/a/show

I got a 404 - File not found error

any ideas or if you need anything from me to help troubleshoot the issue

**Comment by kgrruz** [comment]
I believe this question is more related to https://github.com/lonnieezell/codeigniter-shield.

**Comment by rjwmtgevolution** [comment]
Thank you

I see some updates are coming with Shield and Bonfire2 so I would close
this ticket

Rob


*Robert J. Wilson*Lean Six Sigma Black Belt
President
Meeting Evolution
www.meetingevolution.net
Phone: 949-293-8933
Email: ***@***.***
***@***.***>


*Meeting Evolution ... Your System / Your Code / Your Way*
SCHEDULE A DEMO TODAY
<https://demo.events.meetingevolution.net/index.php/5EFB8C80DD94F-form-record.html?formId=5EFB8C80DD94F>
