### ISSUE TITLE
Cookie bf_consent does not initially exist 

### ISSUE THREAD

**Issue by robertkendrick** [lonnieezell/Bonfire2#126]
Great work Lonnie
PHP: 8.1.4
File: ConsentFilter.php
```
$cookie      = get_cookie('bf_consent');
$permissions = json_decode($cookie, true);    // Fails here because $cookie is NULL.  $cookie cannot be null, deprecated.

// Do we already have consent from the visitor?
// then nothing to do here...
if ($permissions['consent'] ?? false) {
     return;
}
```
Presume just need to check for null and if so go straight to consent form

**Comment by kgrruz** [comment]
I believe even ci4 doesn't support version 8.1.x at the moment. Bonfire2 "follows" him on this subject.

**Comment by robertkendrick** [comment]
Yes, its runs better on PHP 7.4 with fewer problems. I'm sure it will just keep getting better and better.
By the by, Github Codeigniter 4 says required PHP is 7.4 or higher.
Github Bonfire2 says required PHP is same as Codeigniter 4.

**Comment by kgrruz** [comment]
My apologies. I don't checked before answer. You are right: https://github.com/codeigniter4/CodeIgniter4/pull/4883

**Comment by atsanna** [comment]
I solved it this way:
```
        $cookie      = get_cookie('bf_consent');
        if($cookie!=null) {
           $permissions = json_decode($cookie, true);
        }
```
