### ISSUE TITLE
New installation problem: missing composer package codeigniter4/codeigniter4

### ISSUE THREAD

**Issue by atsanna** [lonnieezell/Bonfire2#136]
I encountered an error following the steps outlined in the guide due to missing some requirements.
I tried to fix it, but without success.

These are the steps I performed:

1) composer create-project codeigniter4/appstarter my-app --dev
2) add  "minimum-stability": "dev" in to composer.json:
3) composer update
4) composer require lonnieezell/bonfire --dev

lonnieezell/bonfire dev-develop requires codeigniter4/codeigniter4 dev-develop -> could not be found in any version, there may be a typo in the package name.

**Comment by atsanna** [comment]
I almost solved:

These are the steps I performed:

1) composer create-project codeigniter4/appstarter my-app --dev
2) add in to composer.json:
```
"minimum-stability": "dev",
"repositories": [
		{
			"type": "vcs",
			"url": "https://github.com/codeigniter4/codeigniter4"
		}
	],
```
3) composer update
4) composer require lonnieezell/bonfire --dev
5) php spark bf:install

```
CodeIgniter v4.1.9 Command Line Tool - Server Time: 2022-05-12 06:29:48 UTC-05:00

[ErrorException]

Type of Bonfire\Auth\Config\Auth::$views must be array (as in class CodeIgniter\Shield\Config\Auth)

at VENDORPATH/lonnieezell/bonfire/src/Auth/Config/Auth.php:9

Backtrace:
  1    [internal function]
       CodeIgniter\Debug\Exceptions()->shutdownHandler()
```

**Comment by atsanna** [comment]
I have updated the files
```
Bonfire\Auth\Config\Auth.php
Bonfire\Users\Models\UserModel.php
Bonfire\Consent\Filters\ConsentFilter.php
```
in order to respect the signatures

I fixed the **$folders** variable in **Bonfire\Assets\Config\Assets.php**
`'other' => BFPATH. '../../../../vendor',`

This ensures that the login page is rendered correctly.


The command
`php spark bf:install`

returns
`
Command "bf:install" not found.`

**Comment by ThibautPV** [comment]
Hello,

I also have the same problem (Command "bf:install" not found) + ErrorException
<img width="1242" alt="Capture d’écran 2022-06-30 à 17 58 11" src="https://user-images.githubusercontent.com/75485473/176723835-b46f6611-998c-4ffe-aa96-cc4939589ae9.png">
