### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by qeipami** [lonnieezell/Bonfire2#152]
**php spark bf:install**

Warning: chdir(): No such file or directory (errno 2) in \bonfire\spark on line 42

Call Stack:
    0.2042     398816   1. {main}() \bonfire\spark:0
    0.2054     403224   2. chdir() \bonfire\spark:42

**Fatal error: Uncaught TypeError: Argument 1 passed to CodeIgniter\CLI\Console::__construct() must be an instance of CodeIgniter**\CodeIgniter, int given, called in \bonfire\spark on line 48 and defined in \bonfire\vendor\codeigniter4\framework\system\CLI\Console.php on line 29

TypeError: Argument 1 passed to CodeIgniter\CLI\Console::__construct() must be an instance of CodeIgniter\CodeIgniter, int given, called in \bonfire\spark on line 48 in \bonfire\vendor\codeigniter4\framework\system\CLI\Console.php on line 29

Call Stack:
    0.2042     398816   1. {main}() \bonfire\spark:0
    0.2201     815520   2. CodeIgniter\CLI\Console->__construct() \bonfire\spark:48

**Comment by lonnieezell** [comment]
Oh, this probably needs to be updated to work with the changes in CI 4.2. I'll be working to get Bonfire in a really good spot next week so will tackle this then.

**Comment by lonnieezell** [comment]
This has been fixed to work with CodeIgniter 4.2 and now requires it as a minimum version.
