### ISSUE TITLE
Minor bugs

### ISSUE THREAD

**Issue by joelprestaworks** [lonnieezell/Bonfire2#172]
Hi,

Fantastic work, some minor bugs I found:

I don't know if this should be reported or if you are aware, but core default settings such as Site Name does not render in admin panel but stored in db. Also "Site online" does not work at all (no db value is saved upon change in admin and admin don't remember if should be checked/marked or not).

Edit: also "New user"-button from admin gives:
"Error
Class 'Bonfire\Entities\User' not found"

**Comment by lonnieezell** [comment]
Thanks for these. I am just wrapping up a MAJOR refactor and it sounds like I missed a couple of items. I'll take a look at them.

**Comment by lonnieezell** [comment]
@joelprestaworks I just pushed fixes for those. Let me know if they work for you.
