### ISSUE TITLE
The debug bar disappears

### ISSUE THREAD

**Issue by atsanna** [lonnieezell/Bonfire2#175]
There is some problem between bonfire and the debug bar.

If I run "composer remove lonnieezell/bonfire", everything starts working fine again.

Running "composer require lonnieezell/bonfire" again makes the debug bar disappear

I cannot locate the problem

**Comment by lonnieezell** [comment]
Thanks for reminding me about that. Will look into it in the next few days.

**Comment by atsanna** [comment]
Thank you :)
