### ISSUE TITLE
General Settings error

### ISSUE THREAD

**Issue by kovijanny** [lonnieezell/Bonfire2#178]
Hi Lonnie,

I try to set new "Date & Time format" and I get an error message.
Update: The same error occurs when I change something in "Settings / Users".
Exception
[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Operand type clash: int is incompatible with text
![image](https://user-images.githubusercontent.com/3416204/182018100-709491c2-f691-482a-9609-49e17069e2c9.png)

**Comment by lonnieezell** [comment]
Can you provide more information? Is that from a standard Bonfire db call, or can you share the code that caused this?

**Comment by kovijanny** [comment]
This is by default clean install. 
DB is MsSql, db driver is SQLSRV.
Host Linux, Apache...
In the meantime, I found the problematic code:
VENDORPATH/lonnieezell/bonfire/src/Settings/Controllers/GeneralSettingsController.php : 92   —   setting()

Original this:
setting('Site.siteOnline', $this->request->getPost('siteOnline') === '1');
so it doesn't work.
but yes:
setting('Site.siteOnline', $this->request->getPost('siteOnline'));
