### ISSUE TITLE
number_format(): Passing null to parameter #1 ($num) of type float is deprecated

### ISSUE THREAD

**Issue by WebWanderer007** [lonnieezell/Bonfire2#184]
![image](https://user-images.githubusercontent.com/89518281/182912553-c6da7831-3e43-40c7-80fe-3c03416a2ba3.png)

while clicking on "System info" under the tools menu, facing this issue.

**Comment by lonnie-vault** [comment]
What PHP version?

**Comment by WebWanderer007** [comment]
![image](https://user-images.githubusercontent.com/89518281/182951075-29a378de-7e65-45d1-a835-1869d6c520b0.png)

PHP 8.1.4
