### ISSUE TITLE
suggestion: change in DB data gathering during installation

### ISSUE THREAD

**Issue by dgvirtual** [lonnieezell/Bonfire2#239]
The install procedure could first inquire the user about the intended DB driver, and only then, if needed – about the DB username and password (since, e.g., SQlite3 does not use either).

**Comment by lonnieezell** [comment]
That's a good suggestion. Care to send a PR?

**Comment by dgvirtual** [comment]
Yep, why not. I will presume that sqlite3 only needs db name and table prefix, and all other engines need all config options.

**Comment by lonnieezell** [comment]
Awesome, I appreciate it! And I believe those assumptions are accurate.

**Comment by dgvirtual** [comment]
Submitted a PR #240

**Comment by dgvirtual** [comment]
There is a further question on SQLite3 support. For the Shield user deletion to work with SQLite3 properly, foreign keys need to be enforced (they are not by default, which leaves orphaned database table entries; they would prevent re-adding the same user in the future). Also, to prevent (rare but possible) write clashes there busyTimeout option needs to be set for SQLite3. (this feature will be added to CI 4.3).  Maybe you have a routine on how to solve such issues? Overwrite the Database.php? Add instructions in CLI install file, that would be shown to user in case the SQLite3 is chosen?

I could easily modify your CLI install file to enable it to add those two options to .env file, but the problem is, they are not there  by default in the default database config array in Database.php file (see discussion here: https://github.com/codeigniter4/CodeIgniter4/pull/6939). So, the .env changes would have no effect, the Database.php would need to be edited as well to add those config options.

**Comment by kenjis** [comment]
> Overwrite the Database.php?

I think it is the solution.

**Comment by lonnieezell** [comment]
I agree with @kenjis  - overwrite the Database.php file here.

**Comment by dgvirtual** [comment]
I did it differently – by patching the config file itself #319 (already merged, so closing the issue).
