### ISSUE TITLE
Routing Broken

### ISSUE THREAD

**Issue by Kr3m** [lonnieezell/Bonfire2#296]
I'm not sure what happened here, but I have a Git repo of my website.  It works fine in the production version, but when I tried to install a new development version locally, I can no longer access my default controller with mod_rewrite.

e.g.  browsing to somesite.local/about does not work.  somesite.local/index.php/about does work.

Also, I get the following when trying to run this from CLI:

```
php index.php 
ERROR: 404

Can't find a route for 'cli: /'.
```

**Comment by Kr3m** [comment]
Okay I resolved the first issue by adding this to my local dev site's config, but still have an issue with CLI.

```
<Directory "/path/to/site">
                Options Indexes FollowSymLinks
                AllowOverride All
                Require all granted
</Directory>
```

**Comment by Kr3m** [comment]
This is the code from the Controller that I'm having an issue with:

```
if(is_cli()) {
            $servers_model = new ServersModel();
            $res = $servers_model->getServerInfo();
            $json = array('data' => $res);
            $fp = fopen('./results.json', 'w');
            fwrite($fp, json_encode($json));
            fclose($fp);
            die("CLI command completed. \n");
}
```

**Comment by Kr3m** [comment]
Okay well I seem to have resolved this by adding a new route:

```
$routes->cli
```

This wasn't required before...  Oh well.  At least I got it working.  =D

**Comment by lonnieezell** [comment]
Glad you figured it out. Codeigniter removed support for the uri-style CLI routing a little bit ago. I don't recall the exact version.

**Comment by kenjis** [comment]
The auto routing has been disabled by default since v4.2.0.
See https://codeigniter4.github.io/CodeIgniter4/installation/upgrade_420.html#content-changes

If you install a new CI4 app, the auto routing does not work.

**Comment by Kr3m** [comment]
> The auto routing has been disabled by default since v4.2.0. See https://codeigniter4.github.io/CodeIgniter4/installation/upgrade_420.html#content-changes
> 
> If you install a new CI4 app, the auto routing does not work.

It had nothing to do with auto routing.  CLI used to be able to use $routes->get as well as $routes->cli but that is no longer the case.  I'm not even sure when $routes->cli was introduced, but it's at least a couple of years old.  I don't think it was an option at one point in time or perhaps I just overlooked it since $routes->get worked fine.

There's actually a new version of auto routing for people who use it.  Just not relevant to my situation.
