### ISSUE TITLE
BUG: Email settings do not write SMTPUser field in view email_settings.php

### ISSUE THREAD

**Issue by andersonsousaferreira** [lonnieezell/Bonfire2#3]
The SMTPUser field is not writing correctly to the settings table.

On line 155 of the email_settings.php file, the name attribute needs to be replaced with "SMTPTimeout". **As a result, the SMTPTimeout Key is being duplicated in the database.**

`<input type="number" name="SMTPTimeout" class="form-control" value="<?= old('SMTPTimeout', setting('Email', 'SMTPTimeout')) ?>">`

In lines 94, 141 and 164 of the same file you need to correct the SELECT TAGS with double quotes for better formatting

```
94 - <select name="SMTPPort""
141 - <select name="SMTPCrypto""
164 - <select name="SMTPKeepAlive""
```

**Comment by lonnieezell** [comment]
Thanks for catching this. 

I'm heading out on vacation for a week or so. Are you able to submit a PR with that change?
