### ISSUE TITLE
Bug in bonfire/Modules/Tools/Views/index.php

### ISSUE THREAD

**Issue by jeffstoner** [lonnieezell/Bonfire2#30]
There is a bug with this View component such that if there is a file in the _writable_ directory, it shows up as a number instead of the file's name (and is always unwritable.) This is due to how directory_map() returns results. I have a simple fix to address this and can issue a PR, but I was wondering if we couldn't improve the Filesystem section of the System Info admin area a bit to make it more useful. For instance, since file and directories can exist in the _writable_ area, identifying whether something is a file or directory would be helpful. Perhaps create/last modified timestamps?

**Comment by lonnieezell** [comment]
My original intent was just to show whether or not the main writable directories were actually writable or not. I hadn't considered it a full file-explorer. 

I have no problem with giving it more power. It does seem, though, that if we're showing files there, users would expect to be able to click in directories and continuing exploring. Does that make sense, here, do you think?

**Comment by jeffstoner** [comment]
The _session_ and _cache_ directories would be better served with specialized UI elements given that the data they represent could be decoded into a more user-friendly display. The _logs_ directory already does this in the Logs section. It's the uploads (and any user created directories) that could benefit - but given the limited screen real estate and the potential for the directories to have hundreds/thousands of files and sub-directories, it could get very messy very quickly.

I think keeping it simple and staying in the top-level of _writable_ is best for now. A full-fledged file explorer would probably be overkill, especially for a 1.0 release. Perhaps a re-worked UI implementation for a 2.0/3.0 release or, even better, implemented as a plugin.

I'll rework what's there to give a little more context to the user and send a PR for review. Then you can decide whether to use that or go with the simple 1-line fix I have now.

**Comment by jeffstoner** [comment]
Current implementation. PR coming shortly.

![Bonfire2_FileSystem_revamp](https://user-images.githubusercontent.com/1587365/142500524-50b33be4-8f22-418e-8c80-02aac91aadc3.png)

**Comment by lonnieezell** [comment]
Looks great! Headed over the PR now.

**Comment by jeffstoner** [comment]
Bug resolved with PR #31
