### ISSUE TITLE
Issue installing Bonfire: CI 

### ISSUE THREAD

**Issue by Bliksempie** [lonnieezell/Bonfire2#353]
$ php spark bf:install

Fatal error: Uncaught Error: Failed opening required 'C:\sites\ci4\app\Config/../../vendor/codeigniter4/codeigniter4/system\bootstr
ap.php' (include_path='C:\xampp\php\PEAR') in C:\sites\ci4\spark:75
Stack trace:
#0 {main}
  thrown in C:\sites\ci4\spark on line 75

Get a few of those kind of messages, some warnings, and then the above fatal error. I checked my vendor folder. My CI4 is not in *vendor/codeigniter4/codeigniter4/system* but in *vendor/codeigniter4/framework/system* ... I installed CI4 with composer, so not sure where it goes wrong. I have installed several other packages without issues with this CI4 instance, so I am suspecting an issue with this package, but I am not sure. 

Any ideas?

**Comment by kenjis** [comment]
`vendor/codeigniter4/framework/system` is correct when you install via appstarter.
Fix the `$systemDirectory` value in `app/Config/Paths.php`.

**Comment by Bliksempie** [comment]
Hi Kenji,

Thanks for the feedback. My path in my Paths config says

`public string $systemDirectory = __DIR__ . '/../../vendor/codeigniter4/framework/system';`

But it looks like Bonfire2 is expecting it to be in `public string $systemDirectory = __DIR__ . '/../../vendor/codeigniter4/codeigniter4/system';`

I have installed CI4 with Composer, and it put it there in "framework" folder, and that is where the file physically are located too. So if I change it in the paths manually then other things won't work.

**Comment by kenjis** [comment]
Your error message:
`Fatal error: Uncaught Error: Failed opening required 'C:\sites\ci4\app\Config/../../vendor/codeigniter4/codeigniter4/system\bootstrap.php' (include_path='C:\xampp\php\PEAR') in C:\sites\ci4\spark:75`

`spark` L75:
```php
require rtrim($paths->systemDirectory, '\\/ ') . DIRECTORY_SEPARATOR . 'bootstrap.php';
```

In my understanding, `spark` L75 loads `system/bootstrap.php`. If your `Config\Paths` has:
```php
    public $systemDirectory = __DIR__ . '/../../vendor/codeigniter4/framework/system';
```
It should load `C:\sites\ci4\app\Config/../../vendor/codeigniter4/framework/system\bootstrap.php`.

I don't know why it tries to load `C:\sites\ci4\app\Config/../../vendor/codeigniter4/codeigniter4/system\bootstrap.php`.

**Comment by Bliksempie** [comment]
Thank you - it might then mean my original CI4 installation failed? I can't understand - but everything else works, I just can't get Bonfire installed, so I will skip bonfire until I know more.

**Comment by kenjis** [comment]
I do not know. At least I can't imagine the cause of your error at all. Something strange is happening that is beyond my imagination.
