### ISSUE TITLE
Menu Ordering not working properly

### ISSUE THREAD

**Issue by krishna-gujjjar** [lonnieezell/Bonfire2#376]
I tried `$menuWeight` in the `app/config/Bonfire.php` also `weight` of `MenuItem` in the  `modules/Base/Module.php`, but nothing working to ordering it.

I want the menu order: 
- Dashboard
- Types
- Products
- Users
- Settings
- Tools

Here is the screenshot: 

![app/config/Bonfire.php](https://github.com/lonnieezell/Bonfire2/assets/42290039/04c44c10-359e-417e-a60a-bcc26ed60ce3)

![Screenshot 2023-08-07 at 9 18 52 AM](https://github.com/lonnieezell/Bonfire2/assets/42290039/dee4a5ac-09bc-4f54-9195-435798f9b294)

am i missing something?

**Comment by dgvirtual** [comment]
Are `user_list` and other keys in your array [named routes](https://codeigniter.com/user_guide/incoming/routing.html#named-routes)? The User List's named route should be `user-list` (see `src/Users/Config/Routes.php`):

```php
// Manage Users
$routes->match(['get', 'post'], 'users', 'UserController::list', ['as' => 'user-list']);
```

**Comment by krishna-gujjjar** [comment]
@dgvirtual Yes, there exist all of those named routes in there module's Route Config file.

- `product-list` in `modules/Products/Config/Routes.php`
```php 
$route->match(['get', 'post'], 'products', [ProductController::class, 'list'], ['as' => 'product-list']);
```
- `type-list` in `modules/Base/Config/Routes.php`
```php 
// Manage Types
$route->match(['get', 'post'], 'types', [TypeController::class, 'list'], ['as' => 'type-list']);
```
- `category-list` in `modules/Category/Config/Routes.php`
```php 
$route->match(['get', 'post'], 'categories', [CategoryController::class, 'list'], ['as' => 'category-list']);
```
and `user_list` in `vendor/lonnieezell/bonfire/src/Users/Config/Routes.php`
```php
// Manage Users
$routes->match(['get', 'post'], 'users', 'UserController::list', ['as' => 'user-list']);
```

**Comment by dgvirtual** [comment]
Ok, so, they all contain dashes, not undescores. But you use underscores in $menuWeights property

**Comment by krishna-gujjjar** [comment]
> Ok, so, they all contain dashes, not undescores. But you use underscores in $menuWeights property

Oops, Old habit of mine. I am mostly use underscores rather than dash. 
I replaced routes alias with underscores and it working fine.

Thanks man!
