### ISSUE TITLE
Bonfire routes not working in a fresh installation of Codeigniter 4.4.6?

### ISSUE THREAD

**Issue by atsanna** [lonnieezell/Bonfire2#430]
I tried to do a clean install of CodeIgniter 4.4.6.
I then followed the instructions in the installation.md file.
The database is populated correctly, CodeIgniter works correctly and all expected routes appear in the debug bar.
However, if I go to a Bonfire path, such as /admin or /login, I get a 404 error from Apache.
I can't figure out why Bonfire routes don't work.
At most I would have expected a CodeIgniter error page... 
Has anyone else encountered this problem?
Suggestions on where to look for the problem?

**Comment by dgvirtual** [comment]
Hi, have you tried paths like 

https://yourwebsite.com/index.php/admin/

?

**Comment by dgvirtual** [comment]
See https://codeigniter.com/user_guide/general/urls.html#removing-the-index-php-file on how to get rid of index.php in url

**Comment by atsanna** [comment]
I'm a fool! :D
I forgot about this step.
Thank you so much for your valuable suggestion!!!

**Comment by dgvirtual** [comment]
> I'm a fool! :D I forgot about this step. Thank you so much for your valuable suggestion!!!

Well, to be fair, the Bonfire2 install instructions omit that step while assuming it has been done. Why don't you submit a PR to install instructions regarding this?

**Comment by atsanna** [comment]
Done. Happy to have contributed to this project.
