### ISSUE TITLE
URLs not working in Alias baseURL

### ISSUE THREAD

**Issue by developkariyer** [lonnieezell/Bonfire2#438]
_Hi, first issue entrance, sorry._
Freshly installed codeigniter4 and bonfire2 using composer on a fresh updated Ubuntu 22.04 with Composer 2.2.6
Apache conf:
Alias /ci01 /var/www/html/ci01/public
.env: 
app.baseURL = 'http://localhost/ci01/'

Can login to Bonfire with given username/password during installation. Dashboard comes, OK.
In Dashboard, "Users" icon link under "Quick Links" works as expected. But all other links in the left sidebar ignore alias and try to load from http://localhost/

e.g.: 
Quick Links->Users: http://localhost/ci01/index.php/admin/users
Sidebar->Settings->Consent: http://localhost/admin/settings/consent

If I manually write /ci01/ after localhost, it works but probably link generation fails in sidebar.

Thanks.
Umut.

**Comment by dgvirtual** [comment]
Did you change the public/.htaccess file?

I have this section in mine: 

```
	# If you installed CodeIgniter in a subfolder, you will need to
	# change the following line to match the subfolder you need.
	# http://httpd.apache.org/docs/current/mod/mod_rewrite.html#rewritebase
	# RewriteBase /
```

**Comment by developkariyer** [comment]
I am definitely sure I tried it. However, I gave up and moved away from CI. Thanks for your response...

**Comment by kenjis** [comment]
It seems this is a bug in Bonefine2. Or Bonefine2 does not support baseURL with subfolders.
