### ISSUE TITLE
View not found for component: button-container

### ISSUE THREAD

**Issue by atsanna** [lonnieezell/Bonfire2#449]
The routes

- /admin/settings/users
- /admin/users/1

they return the error

RuntimeException: View not found for component: button-container

on

VENDORPATH/lonnieezell/bonfire/src/View/ComponentRenderer.php on line 231

**Comment by daracorcoran** [comment]
See #434 - it looks like the components will need to be copied into your admin theme

**Comment by atsanna** [comment]
You're right, everything works now.
Thank you so much for your help!

**Comment by dgvirtual** [comment]
Yes, I see we do really need a section on updates in documentation that would list all breaking changes like this one.
