### ISSUE TITLE
View Components need refactoring

### ISSUE THREAD

**Issue by lonnieezell** [lonnieezell/Bonfire2#5]
Currently, use paired tags (`<x-foo></x-foo>`) only works when we override an ini setting. This works fine when you run your own server, but anything on shared hosting will crap out. It does this to store the info in the middle `$slot` of the tags, and hits PHP's built-in limits, so I've currently got those turned off. 

This needs to be refactored to get around this. 

One idea I've had (and is just something rumbling around inside my head) would be to modify the `preg_replace_callback()` being currently used to modify the tag name with a unique id. It would then save the info needed to replace those tags with. This helps ensure that the correct opening/closing tags are discovered, and then the open and close tags would have to be modified separately. 

Not sure if this would work as I think, and I have a feeling it would maybe lose out on some features, but I wanted to include it here so I didn't forget it when I could come back to it. Or if anyone else beats me to it.

**Comment by lonnieezell** [comment]
I fixed an issue with the speed of it, and doesn't seem to need the ini_set to work. However, it is still too greedy. 

For example: 

```html
<x-admin-box> ... stuff ... </x-admin-box>
<x-admin-box> ... stuff ... </x-admin-box>
```

These are currently being grabbed and treated as one big component, instead of two separate ones. 

Need to massage the regex on that one.

**Comment by yassinedoghri** [comment]
Hey @lonnieezell, first off, thanks for your work, looking forward to using Bonfire2 in future projects :)

I've had a similar need to use view components in CI4 and did some research to check out what could be done. Looked at integrating Laravel's Blade at first or creating my own logic but I stumbled on this project and saw you've had a similar implementation.

So, I took out your ComponentRenderer class and adapted it to what I needed. And naturally, I've had the same issues you're facing. I've managed to fix the one you're having currently (i.e. when you declare the same component several times in a row, it breaks).

Removing the `?` after the `<slot>.` seams to fix it:
```diff
- $pattern = '/<\s*x[-\:](?<name>[\w\-\:\.]*?)(?<attributes>[\s\S\=\'\"]*)[^>]?>(?<slot>.*?)<\/\s*x-\1\s*>/uiUsm';
+ $pattern = '/<\s*x[-\:](?<name>[\w\-\:\.]*?)(?<attributes>[\s\S\=\'\"]*)[^>]?>(?<slot>.*)<\/\s*x-\1\s*>/uiUsm';
```
Hopefully it helps!

**Comment by lonnieezell** [comment]
Oh nice! I'll have to give that a go tonight. That didn't slow it way down did it? That was one of the changes I made to get make it less greedy (in theory anyway :) ) which brought my requests from near 700ms for the Email Settings page back down to normal CI speeds. 

Thanks for reporting it, though! And if you have more ideas/updates for that, feel free to submit a PR for it. I'd love to have a great solution we can then maybe rip out into it's own repo.

**Comment by yassinedoghri** [comment]
> That didn't slow it way down did it?

Still super fast CI speed I would say. Haven't tested it thoroughly though, I'll be building UIs with it in the coming weeks, I'll let you know.

> And if you have more ideas/updates for that, feel free to submit a PR for it. I'd love to have a great solution we can then maybe rip out into it's own repo.

One thing I've changed regarding the pattern is having PascalCase named components instead of the blade `x-` naming. I wanted to keep the conventions used in the front-end world as I'm used to them. So, instead of `<x-foo>`, I would have `<Foo>`. Also, apparently it's faster not to have the regex case insensitivity option. I don't know the reason behind the `x-` choice so I may be missing something here.

Another thing I've done is to call the nearest component available to a module. This would allow overwriting components outside of the current module. For example, let's say we have the base app module where we have a `Button` component, and an admin module also with a `Button` component: the admin views would show the `Button` component from the admin module.

**Comment by lonnieezell** [comment]
> Still super fast CI speed I would say. Haven't tested it thoroughly though, I'll be building UIs with it in the coming weeks, I'll let you know.

Sounds great. Thanks! I should be able to make that change tonight and give it a bit of a spin, too. 

> I don't know the reason behind the x- choice so I may be missing something here.

Honestly, I kept it like Laravel had been handling it in this case, mainly because it made a bit of sense if you think about custom header names frequently starting with `x-` (even though the spec deprecated that years ago). I haven't tested it but I would think it might be a little faster since it has that slightly more specific bit, but not really sure. HTML5 prefers to keep everything lowercase, but I believe some of the front-end frameworks do their custom elements with mixed case names, so there's a precedent either way, I'd say.

> Another thing I've done is to call the nearest component available to a module. This would allow overwriting components outside of the current module. For example, let's say we have the base app module where we have a Button component, and an admin module also with a Button component: the admin views would show the Button component from the admin module.

That's a nice touch! If you're up for a quick PR I'd love that change integrated.

**Comment by yassinedoghri** [comment]
> That's a nice touch! If you're up for a quick PR I'd love that change integrated.

Will do!

**Comment by lonnieezell** [comment]
@yassinedoghri thanks! 

Also - just pushed a change removing the `?` and that worked like a charm. Thanks for suggestion on that.
