### ISSUE TITLE
ci bonfire 2 spark

### ISSUE THREAD

**Issue by colonelo** [lonnieezell/Bonfire2#50]
Hi.

I have  installed cibofire2 with composer
When i want to install the rest with spark I am unsuccessful.

create  databse bonfire in localhost 
![bonfire_mysql](https://user-images.githubusercontent.com/24300396/148682515-fed610a3-6ac2-4fc7-9ac1-78c8d7cee26b.JPG)CodeIgniter v4.1.6 Command Line Tool - Server Time: 2022-01-09 05:53:29 UTC-06:00

after that i run the command
![bonfire_spark](https://user-images.githubusercontent.com/24300396/148682651-746a0462-79fb-4aea-9fee-340dcf0758b0.JPG)

what we are doing wrong.

Another quetstion is the possible reinstall with spark when spark  ends unsuccesfuly..or how to run it again initially

![bonfire_spark_2](https://user-images.githubusercontent.com/24300396/148682729-3b239c04-a3b6-4cc2-ab6f-057200098b89.JPG)

Thx in advance 

Matteo, Slovenia, EU

**Comment by colonelo** [comment]
Hi.

I describe the bonfire2 installation process in a new way. 

When I run the lurl application, they don't show it the right way, and the urls are different at different levels of dialing and don't have the same concept. There is no known login utl at the input, when we run the login has the wrong url again, when the dasboard starts the sio url again in a different way.
I describe the installation process after which the urls are not set correctly

here is install process...
  composer create-project lonnieezell/bonfire apph --stability dev
cd apph
Composer update
composer fund
C:\xampp8\htdocs\apph>php spark bf:install

CodeIgniter v4.1.7 Command Line Tool - Server Time: 2022-01-14 06:49:50 UTC-06:00

Creating .env file...Exists

What URL are you running Bonfire under locally? : https://127.0.0.1/app/public/
Database host:  [localhost]: localhost
Database name:  [bonfire]: bonfire
Database username:  [root]: root
Database password:  [root]: root
Database driver: [MySQLi, Postgre, SQLite]: MySQLi
Table prefix: :
Running all new migrations...
        Running: (Sparks\Shield) 2020-12-28-223112_Sparks\Shield\Database\Migrations\CreateAuthTables
        Running: (Sparks\Settings) 2021-07-04-041948_Sparks\Settings\Database\Migrations\CreateSettingsTable
        Running: (App) 2021-09-04-044800_App\Database\Migrations\AdditionalUserFields
        Running: (App) 2021-10-05-040656_App\Database\Migrations\CreateMetaTable

Done migrations.

Create initial user
Email? : mbricelj@gmail.com
First name? : matej
Last name? : bricelj
Username? : matej
Password? : matej
Done. You can now login as a superadmin.

I have environment xampp8 i - apache
When i start the application

![slika](https://user-images.githubusercontent.com/24300396/149522745-ca480653-4fb4-428e-b067-3f68a95226c3.png)

login button url is 127.0.0.1/login which is not exist. 

I think it would be useful for all future users to say the principle that urls on all levels will work with the installation and not to deal with this problem. 

Of course I also did a review of the other urls on the dasboard and these don't work either

Please correct the shortcomings and at least the answer

Regards

**Comment by lonnieezell** [comment]
This could use some additional documentation, but it is not currently designed to handle URL access through a sub-folder, `/app/public`. It currently expects that your domain would point to the `public` folder, as is the default CodeIgniter 4 installation process. 

Looks like you're running through Xampp so you could modify the htaccess file to set the DocumentRoot to point to the correct folder, or you could use the built-in server, `php spark serve`, which would serve it up at `localhost:8080`
