### ISSUE TITLE
bonfire2 testing 

### ISSUE THREAD

**Issue by colonelo** [lonnieezell/Bonfire2#63]
Hi.

I have bonfire2 installed and I am intensively testing it to use the development my new applicatin as soon as possible. During testing, we encounter many questions because some solutions do not work as intended.
for example, when I assign a user new group  "uprabnik" to a user CC and only two permissions

![slika](https://user-images.githubusercontent.com/24300396/149673000-6a2edea7-ce43-4642-ad19-e0a1e23390c7.png)

wheni login with this user with upper permission has all the menus available in dashboard

![slika](https://user-images.githubusercontent.com/24300396/149673151-8ef5af61-46f4-4e0f-96d5-0d541d7f9e78.png)

Of course, I am interested in advance in how you view my intensive testing.
Tell us what your approach is. I am interested in participating in testing. 

I would be happy for additional users guide instructions for use dashboard, and of course a big thank you for your work so far,

Regards

Matteo

**Comment by lonnieezell** [comment]
Thanks for the testing! It's possible on this case that the permissions check got missed when I recently re-did the sidebar. I'll have to check into that. 

I'm happy to accept pull requests to fix any of the issues you find, also!

**Comment by lonnieezell** [comment]
I went through and added in the missing checks for permissions on the sidebar and admin access in general. Thanks for reporting! I was waiting for a number of the automated tests until CI 4.1.6 since there was an issue with feature testing, so now I can get back to improving the test suite.

**Comment by colonelo** [comment]
Thank you very much . I'm already testing further. Since I'm not very good with composer, I ask how to upgrade the latest version or just fix it on my existing installation.
