### ISSUE TITLE
Composer install Ci bonfire2 error when starting

### ISSUE THREAD

**Issue by colonelo** [lonnieezell/Bonfire2#67]
After a fresh installation of Ci bonfire2 and startup of the php spar server -> localhost:8080, the system reports an error

mysqli_sql_exception #1054

Unknown column **'auth_identities.secret'** in 'where clause'
databese  table is 'bf'_ prefixed as you see from other code

![slika](https://user-images.githubusercontent.com/24300396/150498440-874ebe07-7694-4bdc-a003-608755948481.png)

**Comment by lonnieezell** [comment]
Did you run the install script? I can't see any reason why that particular error would crop up since, at least in my old install, that table & column definitely exists. 

I'm running into a different error with a fresh install, though, that seems to happen when just starting the migrations, and appears to be the MigrationRunner having an issue. I need to dig a little more on that.

**Comment by colonelo** [comment]
Just in case, I did a re-installation according to the instructions. The bonfire database was temporarily created before installation. There is still a mistake. 
mysqli_sql_exception #1054

Unknown column 'auth_identities.secret' in 'where clause'
I enclose the installation log.
Please check the log. maybe I'm doing something wrong
[bonfire_2_install.txt](https://github.com/lonnieezell/Bonfire2/files/7917819/bonfire_2_install.txt)

**Comment by lonnieezell** [comment]
Got closer on this last night. I'm seeing the same thing in your log - it has an error before it asks for the email that never creates the table. I think what's going on is that it since it just wrote the information to the env file it doesn't get loaded so it can't access the database. 

Makes sense. I'm guessing during development since it went during multiple passes the database info got written to the env file and then I re-ran the script where it worked, so I never noticed this. 

Thought maybe it was an issue with CI's `BaseConnection::listTables()` method at first so started creating some additional tests for that but they all passed without doing anything. Currently trying to create the db instance locally, and manually run the migrations within the installer. Didn't get it working before I had to stop last night.

**Comment by colonelo** [comment]
Maybe an addition to make it easier to find the bug.

as seen from the first log I first installed the app Bonfire  when I didn't have to create  the database via phpmyadmin.
Does install script not assume creating the database I specify ?
Obviously we have to create it manually !

Then I created the bonfire database Bonfire via phpadmin and ran the installation again, The table created successfuly.
If the database is created, tables are created, but  error in the program remains.

mysqli_sql_exception #1054
Unknown column 'auth_identities.secret' in 'where clause'

**Comment by lonnieezell** [comment]
This should be working now. I had to split the install process into two steps, but this gave me a chance to recommend how to create the database if it's not already created.

**Comment by colonelo** [comment]
I tried to do a fresh installation, Below is a log that doesn't create a database for me.

C:\xampp8\htdocs\app>**php spark bf:install**

CodeIgniter v4.1.7 Command Line Tool - Server Time: 2022-01-27 01:34:48 UTC-06:00

Creating .env file...Done
Setting initial environment

What URL are you running Bonfire under locally? : http://localhost:8080
Database host:  [localhost]: localhost
Database name:  [bonfire]: bonfire
Database username:  [root]: root
Database password:  [root]: root
Database driver: [MySQLi, Postgre, SQLite]: MySQLi
Table prefix: : bf_

If you need to create your database, you may run:
        php spark db:create <database name>

To migrate and create the initial user, please run:
        php spark install --continue


C:\xampp8\htdocs\app>**php spark db:create bonfire**

CodeIgniter v4.1.7 Command Line Tool - Server Time: 2022-01-27 01:36:24 UTC-06:00


[CodeIgniter\Database\Exceptions\DatabaseException]

**Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'bonfire**'

at SYSTEMPATH\Database\BaseConnection.php:407

Backtrace:
  1    SYSTEMPATH\Database\Database.php:67
       CodeIgniter\Database\BaseConnection()->initialize()

  2    SYSTEMPATH\Database\Config.php:105
       CodeIgniter\Database\Database()->loadForge(Object(CodeIgniter\Database\MySQLi\Connection))

  3    SYSTEMPATH\Commands\Database\CreateDatabase.php:137
       CodeIgniter\Database\Config::forge()

  4    SYSTEMPATH\CLI\Commands.php:63
       CodeIgniter\Commands\Database\CreateDatabase()->run([])

  5    SYSTEMPATH\CLI\CommandRunner.php:70
       CodeIgniter\CLI\Commands()->run('db:create', [...])

  6    SYSTEMPATH\CLI\CommandRunner.php:56
       CodeIgniter\CLI\CommandRunner()->index([...])

  7    SYSTEMPATH\CodeIgniter.php:823
       CodeIgniter\CLI\CommandRunner()->_remap('index', 'db:create', 'bonfire')

  8    SYSTEMPATH\CodeIgniter.php:412
       CodeIgniter\CodeIgniter()->runController(Object(CodeIgniter\CLI\CommandRunner))

  9    SYSTEMPATH\CodeIgniter.php:320
       CodeIgniter\CodeIgniter()->handleRequest(null, Object(Config\Cache), false)

 10    SYSTEMPATH\CLI\Console.php:48
       CodeIgniter\CodeIgniter()->run()

 11    ROOTPATH\spark:63
       CodeIgniter\CLI\Console()->run()


C:\xampp8\htdocs\app>

when execute this statement Database service MYSQL  is running under xampp

env file with install

app.baseURL = 'http://localhost:8080'

#--------------------------------------------------------------------
# DATABASE
#--------------------------------------------------------------------

database.default.hostname = localhost
database.default.database = bonfire
database.default.username = root
database.default.password = root
database.default.DBDriver = MySQLi
database.default.DBPrefix = bf_

There is a problem with mysql settings  or ??? 

**ok then i manual create **bonfire** database via phpmyadmin**

C:\xampp8\htdocs\app>php spark install --continue

CodeIgniter v4.1.7 Command Line Tool - Server Time: 2022-01-27 02:01:10 UTC-06:00

Command "install" not found.

Did you mean this?
    bf:install


C:\xampp8\htdocs\app>php spark bf:install --continue

CodeIgniter v4.1.7 Command Line Tool - Server Time: 2022-01-27 02:01:33 UTC-06:00

Running all new migrations...
        Running: (Sparks\Shield) 2020-12-28-223112_Sparks\Shield\Database\Migrations\CreateAuthTables
        Running: (Sparks\Settings) 2021-07-04-041948_Sparks\Settings\Database\Migrations\CreateSettingsTable
        Running: (App) 2021-09-04-044800_App\Database\Migrations\AdditionalUserFields
        Running: (App) 2021-10-05-040656_App\Database\Migrations\CreateMetaTable
Done migrations.

Create initial user
Email? : mbricelj@gmail.com
First name? : matej
Last name? : bricelj
Username? : matej
Password? : matej
Done. You can now login as a superadmin.

**Now database tabel is created**

when i want to login with localhost :8080

error is still exist

![slika](https://user-images.githubusercontent.com/24300396/151317109-17b37aae-b315-45d0-951f-759d4bb6b0c7.png)

**Comment by lonnieezell** [comment]
It sounds like your database settings are incorrect. One common issue I see is that localhost doesn't work for a specific setup. Trying using 127.0.0.1 instead.

**Comment by colonelo** [comment]
I change the database instead of localhost to 127.0.0.1  ".env" file is changed but result is the same

when i install via ms.dos i stared the xampp where is my database link.

![slika](https://user-images.githubusercontent.com/24300396/151413454-9f65ee32-2e97-455e-9aa3-0db65e52c4ec.png)

Maybe I’m already consuming more energy to install. I will manually adjust these matters to make the application work. Since I want the project to move forward, I ask you what the development tasks are and what would make sense to test in the first phase  Of course, I would like to make my html views based on your admin form (html views).
Are you already preparing somethings for this topic and what the plan is.?

**Comment by colonelo** [comment]
It didn't give me peace. Today I did the installation again according to the following procedure.

C:\xampp8\htdocs\app>**php spark db:create bonfire** (1)
CodeIgniter v4.1.7 Command Line Tool - Server Time: 2022-01-28 01:17:27 UTC-06:00
Database "bonfire" successfully created.


C:\xampp8\htdocs\app>**php spark bf:instal**l (2)
CodeIgniter v4.1.7 Command Line Tool - Server Time: 2022-01-28 01:18:27 UTC-06:00
Creating .env file...Done
Setting initial environment

What URL are you running Bonfire under locally? : **http://localhost:8080**
Database host:  [localhost]: **localhost**
Database name:  [bonfire]: bonfire
Database username:  [root]: root
Database password:  [root]:
Database driver: [MySQLi, Postgre, SQLite]: MySQLi
Table prefix: : bf_

If you need to create your database, you may run:
        php spark db:create <database name>

To migrate and create the initial user, please run:
        php spark install --continue

C:\xampp8\htdocs\app>**php spark install --continue (wrong guide !!)_**
CodeIgniter v4.1.7 Command Line Tool - Server Time: 2022-01-28 01:20:19 UTC-06:00
Command "install" not found.

Did you mean this?
    bf:install
C:\xampp8\htdocs\app>**php spark bf:install --continue** (3)
CodeIgniter v4.1.7 Command Line Tool - Server Time: 2022-01-28 01:20:33 UTC-06:00

Running all new migrations...
        Running: (Sparks\Shield) 2020-12-28-223112_Sparks\Shield\Database\Migrations\CreateAuthTables
        Running: (Sparks\Settings) 2021-07-04-041948_Sparks\Settings\Database\Migrations\CreateSettingsTable
        Running: (App) 2021-09-04-044800_App\Database\Migrations\AdditionalUserFields
        Running: (App) 2021-10-05-040656_App\Database\Migrations\CreateMetaTable
Done migrations.

Create initial user
Email? : mxxxxx@gmail.com
First name? : matej
Last name? : xxxxxx
Username? : matej
Password? : matej
Done. You can now login as a superadmin.


when start the aplication login 
**http://localhost:8080/login** (4)
the čast version have still error in **one** statement  👍 

![slika](https://user-images.githubusercontent.com/24300396/151505794-01cf062b-3d30-4e0f-bb5a-999faf49970b.png)

**Comment by lonnieezell** [comment]
Oh! that's an issue with Shield. Seems it doesn't like having a table prefix. I'll try to get that working tonight or tomorrow. Thanks for sticking with it! If you try the install again without the prefix I think it should work.

**Comment by colonelo** [comment]
the problem is in syntax on line. 32

**vendor\lonnieezell\codigniter-shield\src\Authentication\Traits\UserProvider.php:                ->where('LOWER(auth_identities.secret)', strtolower($email));**

if i turn off the function LOWER then everything works, with prefixed table in MYsql

![slika](https://user-images.githubusercontent.com/24300396/151571489-c5475ca0-2d80-46e8-8841-30c907327aa9.png)

**Comment by lonnieezell** [comment]
Correct. There were two locations in that method that needed adjusted. I've updated Shield so `composer update` should get you up and running there.
