### ISSUE TITLE
scss  folder inside themes/Admin is missing ??

### ISSUE THREAD

**Issue by churavka** [lonnieezell/Bonfire2#77]
webpackmix.js points to the missing scss directory in themes / Admin.
There is already a css file already generated.
package.json is missing to generate from IDE (npx mix watch)

Thank you

https://github.com/lonnieezell/Bonfire2/blob/6420c8acb0f1a3b99a730ed39c17f072497f30e0/webpack.mix.js#L4

**Comment by churavka** [comment]
Asset is loaded directly from Controller, but if asset contain local images is better move all with webpackmix.js to public folder?

**Comment by lonnieezell** [comment]
I ended up not using Mix or SASS at all and opted to keep it simple. I haven't cleaned up all of the remnants of that yet. 

Any chance you want to submit a PR to clean that up?

**Comment by churavka** [comment]
Maybe it's right :).
https://github.com/lonnieezell/Bonfire2/pull/79
