### ISSUE TITLE
Bonfire Installer -  XAMPP for windows

### ISSUE THREAD

**Issue by colonelo** [lonnieezell/Bonfire2#78]
i have done the usual bonfire installation via localhost: 8080 works for me.
But i want to execute system on xampp service apache and mysql the system routes not working

If I change the .env and app files. php on 127.0.0.1 and apache http.conf according to the instructions in my document root does not work at all. It tempts me to test performance under this environment as it will be the same as in production, Pictured is my file structure. I have already looked at the variants, I see that php serve uses its own settings, which are not suitable for development, as we will have problems with production. You can help us with advice, and I'll do my best with testing,

![slika](https://user-images.githubusercontent.com/24300396/151808637-f36d7dde-61cb-4ff1-b28a-40f19021ab81.png)

When i starded via xampp with manual input 

https://127.0.0.1/app/public/

![slika](https://user-images.githubusercontent.com/24300396/151808910-3a498df8-5726-466c-aa10-df49e3a6a993.png)
 
the root system is not recognize via routes settings, (document_root, base_url.....i dont know)

login url points to url without routes settings 

![slika](https://user-images.githubusercontent.com/24300396/151809172-c7f60e75-5e2d-4dee-a90b-906023f51c15.png)

Apparently the local server has its own settings and procedures ?

**Comment by lonnieezell** [comment]
Like CodeIgniter in general, It's not designed to run from a sub-folder without modifications. I'm not a devops guy, and haven't used Apache in awhile, but [this tutorial](https://jaironlanda.com/blog/CodeIgniter/how-to-install-codeigniter-4-in-xampp-windows-10) looks to cover it for you.

**Comment by colonelo** [comment]
Firts thanks for your time and hints

I followed the instructions for XAMPP and codeigniter  and successfully started BONFIRE2 via xampp.

here is the additional info for other users which must be set for the login system  to work

**.env file**
 app.baseURL = 'http://ci4site.test'
**App.php** 
  public $baseURL = 'http://ci4site.test';

after a successful login, the menus work.

I continue to test the functionality BONFIRE via XAMPP environment

![slika](https://user-images.githubusercontent.com/24300396/151944660-4e034912-1c3d-4dba-a787-000d5568cd7a.png)
![slika](https://user-images.githubusercontent.com/24300396/151945350-af18fca5-ef19-4b5f-92c9-26987a4aeaea.png)
I see that additional matters are being supplemented
