### ISSUE TITLE
Email parameters and send mail  via magic-link

### ISSUE THREAD

**Issue by colonelo** [lonnieezell/Bonfire2#81]
I have made my own settings in the email bonfire,
![slika](https://user-images.githubusercontent.com/24300396/152118143-69c2e32d-d861-40bf-be2e-c09d742e0881.png)

however, the e-mail sending procedure wants to be sent via other parameters, 
The program does not return an error to the user, but it is in the system log

![slika](https://user-images.githubusercontent.com/24300396/152117647-9e9e8be0-885f-4266-8771-8acafb94fc61.png)

LOGS
<html><body>
<h2>Logs <span></span></h2>				

Severity | Message
-- | --
error | Email: sendWithMail throwed mail(): Failed to connect to  mailserver at &quot;**localhost&quot; port 465,** verify your  &quot;SMTP&quot; and &quot;smtp_port&quot; setting in  php.ini or use ini_set()

</body>
</html>

**Comment by lonnieezell** [comment]
Thanks for this one. Shield was not pulling the email from the settings lib, though it uses settings everywhere else, so I created a new helper method for it  to get the email library and initialize it with settings from the db if available.

**Comment by colonelo** [comment]
After action
composer update
C:\xampp8\htdocs\app>composer update
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 18 updates, 1 removal
  - Removing symfony/polyfill-php73 (v1.24.0)
  - Upgrading codeigniter4/settings (v1.0.0 => v2.1.0)
  - Upgrading composer/pcre (1.0.0 => 1.0.1)
  - Upgrading fakerphp/faker (v1.18.0 => v1.19.0)
  - Upgrading lonnieezell/codigniter-shield (dev-develop 1db163e => dev-develop d3a9a1c)
  - Upgrading phpstan/phpstan (1.4.3 => 1.4.5)
  - Upgrading psr/cache (1.0.1 => 3.0.0)
  - Upgrading roave/security-advisories (dev-latest 38da7ef => dev-latest 0c86f70)
  - Upgrading symfony/console (v5.4.2 => v6.0.3)
  - Upgrading symfony/deprecation-contracts (v2.5.0 => v3.0.0)
  - Upgrading symfony/event-dispatcher (v5.4.0 => v6.0.3)
  - Upgrading symfony/event-dispatcher-contracts (v2.5.0 => v3.0.0)
  - Upgrading symfony/filesystem (v5.4.0 => v6.0.3)
  - Upgrading symfony/finder (v5.4.2 => v6.0.3)
  - Upgrading symfony/options-resolver (v5.4.0 => v6.0.3)
  - Upgrading symfony/process (v5.4.2 => v6.0.3)
  - Downgrading symfony/service-contracts (v2.5.0 => v2.4.1)
  - Upgrading symfony/stopwatch (v5.4.0 => v6.0.3)
  - Upgrading symfony/string (v5.4.2 => v6.0.3)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 18 updates, 1 removal
  - Downloading fakerphp/faker (v1.19.0)
  - Downloading lonnieezell/codigniter-shield (dev-develop d3a9a1c)
  - Downloading phpstan/phpstan (1.4.5)
  - Removing symfony/polyfill-php73 (v1.24.0)
  - Downgrading symfony/service-contracts (v2.5.0 => v2.4.1): Extracting archive
  - Upgrading symfony/stopwatch (v5.4.0 => v6.0.3): Extracting archive
  - Upgrading symfony/process (v5.4.2 => v6.0.3): Extracting archive
  - Upgrading symfony/deprecation-contracts (v2.5.0 => v3.0.0): Extracting archive
  - Upgrading symfony/options-resolver (v5.4.0 => v6.0.3): Extracting archive
  - Upgrading symfony/finder (v5.4.2 => v6.0.3): Extracting archive
  - Upgrading symfony/filesystem (v5.4.0 => v6.0.3): Extracting archive
  - Upgrading symfony/event-dispatcher-contracts (v2.5.0 => v3.0.0): Extracting archive
  - Upgrading symfony/event-dispatcher (v5.4.0 => v6.0.3): Extracting archive
  - Upgrading symfony/string (v5.4.2 => v6.0.3): Extracting archive
  - Upgrading symfony/console (v5.4.2 => v6.0.3): Extracting archive
  - Upgrading psr/cache (1.0.1 => 3.0.0): Extracting archive
  - Upgrading composer/pcre (1.0.0 => 1.0.1): Extracting archive
  - Upgrading fakerphp/faker (v1.18.0 => v1.19.0): Extracting archive
  - Upgrading codeigniter4/settings (v1.0.0 => v2.1.0): Extracting archive
  - Upgrading lonnieezell/codigniter-shield (dev-develop 1db163e => dev-develop d3a9a1c): Extracting archive
  - Upgrading phpstan/phpstan (1.4.3 => 1.4.5): Extracting archive
  - Upgrading roave/security-advisories (dev-latest 38da7ef => dev-latest 0c86f70)
Generating autoload files
56 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

error is still exist
![slika](https://user-images.githubusercontent.com/24300396/152490231-63612322-e406-4be5-acdb-b18a4487b1f4.png)

I forgot something ?

**Comment by colonelo** [comment]
If I reinstall the app from the beginning it now works.

composer create-project lonnieezell/bonfire app --stability dev
php spark bf:install
CodeIgniter v4.1.8 Command Line Tool - Server Time: 2022-02-04 02:14:27 UTC-06:00
Creating .env file...Done
Setting initial environment

What URL are you running Bonfire under locally? : http://ci4site.test
etc...

![slika](https://user-images.githubusercontent.com/24300396/152497676-446c6389-6c7b-40c6-aa54-68d9d1478507.png)


![slika](https://user-images.githubusercontent.com/24300396/152497470-084df14a-6a78-4a9d-b3f6-c176355f4860.png)


thanks
