### ISSUE TITLE
CRUD Generator

### ISSUE THREAD

**Issue by digicomsujan** [lonnieezell/Bonfire2#82]
Hi, I used to use bonfire (ci3) version, and I recently switched to ci4 so was wandering will this version of bonfire also have module generator like previous version.

**Comment by lonnieezell** [comment]
That is planned yes. CI4 already has code generators that are similar to parts of what Bonfire 1 provided, though we definitely need some customized ones that get views setup etc.

**Comment by treborin** [comment]
@digicomsujan , you could try this: https://forum.codeigniter.com/thread-77877.html
It works very well doing its job, as a base. There's a video too for you to see.
Well, i hope it helps you :)
It's here on github too: https://github.com/Adel-Qusay/Codeigniter-4-CRUD-generator
