### ISSUE TITLE
Bonfire 2 web hosting 

### ISSUE THREAD

**Issue by colonelo** [lonnieezell/Bonfire2#89]
Maybe I was one of the first to play around with installing bonfire 2 on web hosting.

On my testing environment localhost  via apache xampp environment httpd-vhosts everything works for me because I have access to apache config files.
However, we know that we do not have access to apache config (eg httpd-vhosts etc) files on the hosting, except
local .htacces.

So I read the instructions on how to set up the case via .htacess
I set it to the root folder
/domains/brikelli.eu/public_html/ci4
where the bonfire 2 application is installed - ci4.brikelli.eu

.Htaccess content

RewriteEngine on
RewriteCond% {HTTP_HOST} ^ ci4.brikelli.eu $ [NC, OR]
RewriteCond% {HTTP_HOST} ^ ci4.brikelli.eu $
RewriteCond% {REQUEST_URI}! / App / public /
RewriteRule (. *) / App / public / $ 1 [L]

The BONFIRE settings on the host are

.env setting is app.baseURL = 'http://ci4.brikelli.eu/'
App setting is public $ baseURL = 'http://ci4.brikelli.eu/';

If you click on URl
http://ci4.brikelli.eu/

The call works by calling the dasboard
However, when I click login, the call loses the status 404 not found

I ask for an expert opinion. I can also help with instructions if you guide me.
We definitely need to make instructions for other users not to waste time with installations but to develop applications with this system. I am sure that this way more users will join.

i read a lot on the forums i think they need to make uniform instructions

Matteo, Ljubljana Slovenia

**Comment by kgrruz** [comment]
I'm not an expert. I believe the rule used is just redirecting the main url. Try this:
```
RewriteEngine on
RewriteBase /
RewriteCond %{REQUEST_URI} !^/ci4/
RewriteCond %{HTTP_HOST} ci4.brikelli.eu
RewriteRule ^(.*)$ /ci4/public/$1 [L]
```

**Comment by colonelo** [comment]
i tried your setting on the folder
/domains/brikelli.eu/public_html/ci4/.htaccess

![slika](https://user-images.githubusercontent.com/24300396/153471190-981c327a-cd98-47aa-a3c0-752012f254a1.png)

as we see it does not work.

Nowhere is it traced how this is set up for codeigniter4

**Comment by colonelo** [comment]
The problem is nt in document_root.

Proble is with assets_helper which produced 
file cache busting
htdocs\app\bonfire\Modules\Assets\Helpers\assets_helper.php
what are the conditions on web hosting that make it work
HERE Is the status error
![slika](https://user-images.githubusercontent.com/24300396/153713026-d73eef84-52f6-45d0-905b-bf5f5b8dbcfd.png)

maybe anyone knows where 
Status
404
Not Found
strict-origin-when-cross-origin

**Comment by colonelo** [comment]
Obviously there is not enough interest for the project and no one has experience with it so I am closing the unsolved case.
