### ISSUE TITLE
Need Empty option on Encryption field into Mail Settings

### ISSUE THREAD

**Issue by treborin** [lonnieezell/Bonfire2#99]
Hi,
When you use smtp protocol for email sending, if you select port 465, you must to leave blank the Encryption field, otherwise sending emails do not works (as indicated in CI4 official docu).
So we need one more option in that field (3 total): TLS, SSL, and none.

Congrats for such a great job with this fantastic tool, Bonfire2!!

**Comment by lonnieezell** [comment]
Good catch, thanks!  

I'm glad you're liking it so far! It's not complete, yet, but the main parts are some CLI generator commands and more work on the documentation (writing some more, fixing next/previous links, and getting it to recognize docs in third-party libraries (like the Auth package, Shield, so I don't have to write those docs twice lol). At that point I think it'll be good for a 1.0 release. 

I've started working on a personal project that I've been wanting to do for years, but have been too busy building CI4 and Bonfire to do. That will help me find weak points in the code or documentation. If you run across anything drop a note in the Discussions area and we can talk about it. And feel free to submit PR's to fix things or add new features! 

Working on this fix now.
